import type { Metadata } from 'next'
import '../app/globals.css'
import Navbar from '@/components/Navbar'
import ReduxProvider from '@/store/ReduxProvider' // Redux Provider'ı import ettik

type RootLayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
